// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Admissions_Scoring_Engine.Data;

#nullable disable

namespace University_Admissions_Scoring_Engine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321201503_MakeKierunekAlgorytmNullable")]
    partial class MakeKierunekAlgorytmNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Algorytm", b =>
                {
                    b.Property<int>("IdAlgorytm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgorytm"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlgorytm");

                    b.ToTable("Algorytm", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmGrupa", b =>
                {
                    b.Property<int>("IdAlgorytmGrupa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgorytmGrupa"));

                    b.Property<int>("AlgorytmMaturaId")
                        .HasColumnType("int");

                    b.Property<int>("AlgorytmOperacjaId")
                        .HasColumnType("int");

                    b.Property<int?>("AlgorytmOperacjaIdAlgorytmOperacja")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimalnePunkty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RodzicId")
                        .HasColumnType("int");

                    b.HasKey("IdAlgorytmGrupa");

                    b.HasIndex("AlgorytmMaturaId");

                    b.HasIndex("AlgorytmOperacjaId");

                    b.HasIndex("AlgorytmOperacjaIdAlgorytmOperacja");

                    b.HasIndex("RodzicId");

                    b.ToTable("AlgorytmGrupa", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmLicz", b =>
                {
                    b.Property<int>("IdAlgorytmLicz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgorytmLicz"));

                    b.Property<int>("AlgorytmGrupaId")
                        .HasColumnType("int");

                    b.Property<bool>("CzyWymagany")
                        .HasColumnType("bit");

                    b.Property<decimal>("Liczba")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinimalnePunkty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PrzedmiotRodzajPoziomId")
                        .HasColumnType("int");

                    b.HasKey("IdAlgorytmLicz");

                    b.HasIndex("AlgorytmGrupaId");

                    b.HasIndex("PrzedmiotRodzajPoziomId");

                    b.ToTable("AlgorytmLicz", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmMatura", b =>
                {
                    b.Property<int>("IdAlgorytmMatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgorytmMatura"));

                    b.Property<int>("AlgorytmId")
                        .HasColumnType("int");

                    b.Property<int>("MaturaId")
                        .HasColumnType("int");

                    b.HasKey("IdAlgorytmMatura");

                    b.HasIndex("MaturaId");

                    b.HasIndex("AlgorytmId", "MaturaId")
                        .IsUnique();

                    b.ToTable("AlgorytmMatura", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmOperacja", b =>
                {
                    b.Property<int>("IdAlgorytmOperacja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgorytmOperacja"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlgorytmOperacja");

                    b.ToTable("AlgorytmOperacja", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Kandydat", b =>
                {
                    b.Property<int>("IdKandydat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKandydat"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdKandydat");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kandydat", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatDyplom", b =>
                {
                    b.Property<int>("IdKandydatDyplom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKandydatDyplom"));

                    b.Property<int>("KandydatId")
                        .HasColumnType("int");

                    b.Property<int>("MaturaId")
                        .HasColumnType("int");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.HasKey("IdKandydatDyplom");

                    b.HasIndex("KandydatId");

                    b.HasIndex("MaturaId");

                    b.HasIndex("Numer")
                        .IsUnique();

                    b.ToTable("KandydatDyplom", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatDyplomPrzedmiot", b =>
                {
                    b.Property<int>("IdKandydatDyplomPrzedmiot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKandydatDyplomPrzedmiot"));

                    b.Property<int>("KandydatDyplomId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotRodzajPoziomId")
                        .HasColumnType("int");

                    b.Property<decimal>("Punkty")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdKandydatDyplomPrzedmiot");

                    b.HasIndex("PrzedmiotRodzajPoziomId");

                    b.HasIndex("KandydatDyplomId", "PrzedmiotRodzajPoziomId")
                        .IsUnique();

                    b.ToTable("KandydatDyplom_Przedmiot", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatKierunek", b =>
                {
                    b.Property<int>("IdKandydatKierunek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKandydatKierunek"));

                    b.Property<int>("KandydatId")
                        .HasColumnType("int");

                    b.Property<int>("KierunekId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Punkty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Ranking")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("IdKandydatKierunek");

                    b.HasIndex("KierunekId");

                    b.HasIndex("StatusId");

                    b.HasIndex("KandydatId", "KierunekId")
                        .IsUnique();

                    b.ToTable("Kandydat_Kierunek", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Kierunek", b =>
                {
                    b.Property<int>("IdKierunek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKierunek"));

                    b.Property<int?>("AlgorytmId")
                        .HasColumnType("int");

                    b.Property<int>("MaxListaRezerwowa")
                        .HasColumnType("int");

                    b.Property<int>("MaxPrzyjetych")
                        .HasColumnType("int");

                    b.Property<int>("MinPrzyjetych")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RodzajId")
                        .HasColumnType("int");

                    b.Property<int>("TrybId")
                        .HasColumnType("int");

                    b.HasKey("IdKierunek");

                    b.HasIndex("AlgorytmId");

                    b.HasIndex("RodzajId");

                    b.HasIndex("TrybId");

                    b.ToTable("Kierunek", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KierunekRodzaj", b =>
                {
                    b.Property<int>("IdRodzaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRodzaj"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRodzaj");

                    b.ToTable("KierunekRodzaj", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KierunekTryb", b =>
                {
                    b.Property<int>("IdTryb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTryb"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTryb");

                    b.ToTable("KierunekTryb", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Matura", b =>
                {
                    b.Property<int>("IdMatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatura"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SkalaDo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SkalaOd")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SkalaUnit")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdMatura");

                    b.ToTable("Matura", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.MaturaPrzedmiot", b =>
                {
                    b.Property<int>("IdMaturaPrzedmiot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaturaPrzedmiot"));

                    b.Property<int>("MaturaId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotRodzajPoziomId")
                        .HasColumnType("int");

                    b.HasKey("IdMaturaPrzedmiot");

                    b.HasIndex("PrzedmiotRodzajPoziomId");

                    b.HasIndex("MaturaId", "PrzedmiotRodzajPoziomId")
                        .IsUnique();

                    b.ToTable("Matura_Przedmiot", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Przedmiot", b =>
                {
                    b.Property<int>("IdPrzedmiot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedmiot"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPrzedmiot");

                    b.ToTable("Przedmiot", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotPoziom", b =>
                {
                    b.Property<int>("IdPrzedmiotPoziom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedmiotPoziom"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPrzedmiotPoziom");

                    b.ToTable("PrzedmiotPoziom", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzaj", b =>
                {
                    b.Property<int>("IdPrzedmiotRodzaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedmiotRodzaj"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPrzedmiotRodzaj");

                    b.ToTable("PrzedmiotRodzaj", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", b =>
                {
                    b.Property<int>("IdPrzedmiotRodzajPoziom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedmiotRodzajPoziom"));

                    b.Property<int>("PrzedmiotId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotPoziomId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotRodzajId")
                        .HasColumnType("int");

                    b.HasKey("IdPrzedmiotRodzajPoziom");

                    b.HasIndex("PrzedmiotPoziomId");

                    b.HasIndex("PrzedmiotRodzajId");

                    b.HasIndex("PrzedmiotId", "PrzedmiotRodzajId", "PrzedmiotPoziomId")
                        .IsUnique();

                    b.ToTable("Przedmiot_Rodzaj_Poziom", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdStatus");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmGrupa", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.AlgorytmMatura", "AlgorytmMatura")
                        .WithMany("Grupy")
                        .HasForeignKey("AlgorytmMaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.AlgorytmOperacja", "AlgorytmOperacja")
                        .WithMany()
                        .HasForeignKey("AlgorytmOperacjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.AlgorytmOperacja", null)
                        .WithMany("AlgorytmGrupy")
                        .HasForeignKey("AlgorytmOperacjaIdAlgorytmOperacja");

                    b.HasOne("University_Admissions_Scoring_Engine.Models.AlgorytmGrupa", "Rodzic")
                        .WithMany()
                        .HasForeignKey("RodzicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlgorytmMatura");

                    b.Navigation("AlgorytmOperacja");

                    b.Navigation("Rodzic");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmLicz", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.AlgorytmGrupa", "AlgorytmGrupa")
                        .WithMany("Elementy")
                        .HasForeignKey("AlgorytmGrupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", "PrzedmiotRodzajPoziom")
                        .WithMany("AlgorytmLicze")
                        .HasForeignKey("PrzedmiotRodzajPoziomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlgorytmGrupa");

                    b.Navigation("PrzedmiotRodzajPoziom");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmMatura", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Algorytm", "Algorytm")
                        .WithMany("AlgorytmyMatur")
                        .HasForeignKey("AlgorytmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.Matura", "Matura")
                        .WithMany()
                        .HasForeignKey("MaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Algorytm");

                    b.Navigation("Matura");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatDyplom", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Kandydat", "Kandydat")
                        .WithMany("KandydatDyplomy")
                        .HasForeignKey("KandydatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.Matura", "Matura")
                        .WithMany("KandydatDyplomy")
                        .HasForeignKey("MaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kandydat");

                    b.Navigation("Matura");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatDyplomPrzedmiot", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.KandydatDyplom", "KandydatDyplom")
                        .WithMany("KandydatDyplomPrzedmioty")
                        .HasForeignKey("KandydatDyplomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", "PrzedmiotRodzajPoziom")
                        .WithMany("KandydatDyplomPrzedmioty")
                        .HasForeignKey("PrzedmiotRodzajPoziomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KandydatDyplom");

                    b.Navigation("PrzedmiotRodzajPoziom");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatKierunek", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Kandydat", "Kandydat")
                        .WithMany("KandydatKierunki")
                        .HasForeignKey("KandydatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.Kierunek", "Kierunek")
                        .WithMany("KandydatKierunki")
                        .HasForeignKey("KierunekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.Status", "Status")
                        .WithMany("KandydatKierunki")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kandydat");

                    b.Navigation("Kierunek");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Kierunek", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Algorytm", "Algorytm")
                        .WithMany()
                        .HasForeignKey("AlgorytmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("University_Admissions_Scoring_Engine.Models.KierunekRodzaj", "Rodzaj")
                        .WithMany("Kierunki")
                        .HasForeignKey("RodzajId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.KierunekTryb", "Tryb")
                        .WithMany("Kierunki")
                        .HasForeignKey("TrybId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Algorytm");

                    b.Navigation("Rodzaj");

                    b.Navigation("Tryb");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.MaturaPrzedmiot", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Matura", "Matura")
                        .WithMany("MaturaPrzedmioty")
                        .HasForeignKey("MaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", "PrzedmiotRodzajPoziom")
                        .WithMany("MaturaPrzedmioty")
                        .HasForeignKey("PrzedmiotRodzajPoziomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matura");

                    b.Navigation("PrzedmiotRodzajPoziom");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", b =>
                {
                    b.HasOne("University_Admissions_Scoring_Engine.Models.Przedmiot", "Przedmiot")
                        .WithMany("PrzedmiotRodzajPoziomy")
                        .HasForeignKey("PrzedmiotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.PrzedmiotPoziom", "PrzedmiotPoziom")
                        .WithMany("PrzedmiotRodzajPoziomy")
                        .HasForeignKey("PrzedmiotPoziomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzaj", "PrzedmiotRodzaj")
                        .WithMany("PrzedmiotRodzajPoziomy")
                        .HasForeignKey("PrzedmiotRodzajId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Przedmiot");

                    b.Navigation("PrzedmiotPoziom");

                    b.Navigation("PrzedmiotRodzaj");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Algorytm", b =>
                {
                    b.Navigation("AlgorytmyMatur");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmGrupa", b =>
                {
                    b.Navigation("Elementy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmMatura", b =>
                {
                    b.Navigation("Grupy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.AlgorytmOperacja", b =>
                {
                    b.Navigation("AlgorytmGrupy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Kandydat", b =>
                {
                    b.Navigation("KandydatDyplomy");

                    b.Navigation("KandydatKierunki");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KandydatDyplom", b =>
                {
                    b.Navigation("KandydatDyplomPrzedmioty");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Kierunek", b =>
                {
                    b.Navigation("KandydatKierunki");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KierunekRodzaj", b =>
                {
                    b.Navigation("Kierunki");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.KierunekTryb", b =>
                {
                    b.Navigation("Kierunki");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Matura", b =>
                {
                    b.Navigation("KandydatDyplomy");

                    b.Navigation("MaturaPrzedmioty");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Przedmiot", b =>
                {
                    b.Navigation("PrzedmiotRodzajPoziomy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotPoziom", b =>
                {
                    b.Navigation("PrzedmiotRodzajPoziomy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzaj", b =>
                {
                    b.Navigation("PrzedmiotRodzajPoziomy");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.PrzedmiotRodzajPoziom", b =>
                {
                    b.Navigation("AlgorytmLicze");

                    b.Navigation("KandydatDyplomPrzedmioty");

                    b.Navigation("MaturaPrzedmioty");
                });

            modelBuilder.Entity("University_Admissions_Scoring_Engine.Models.Status", b =>
                {
                    b.Navigation("KandydatKierunki");
                });
#pragma warning restore 612, 618
        }
    }
}
